;C    d1 n1 -- n2 n3   floored signed div'n
;                            courtesy of Ed Smeda
    HEADER(FMSLASHMOD,6,"fm/mod",DOCOLON)
        DW XT_DUP,XT_TO_R,XT_2DUP,XT_XOR,XT_TO_R,XT_TO_R
        DW XT_DABS,XT_R_FETCH,XT_ABS,XT_UMSLASHMOD
        DW XT_SWAP,XT_R_FROM,XT_QNEGATE,XT_SWAP,XT_R_FROM,XT_ZEROLESS,XT_DOCONDBRANCH
        DEST(FMMOD1)
        DW XT_NEGATE,XT_OVER,XT_DOCONDBRANCH
        DEST(FMMOD2)
        DW XT_R_FETCH,XT_ROT,XT_MINUS,XT_SWAP,XT_1MINUS
FMMOD2: 
FMMOD1: DW XT_R_FROM,XT_DROP,XT_EXIT
